%% Mini detection 
% Run this script in sections (aka 'cells') using the 'Run section' button,
% rather than running it all at once. Numbered items should be read and
% relevent settings set by user
%
%    
% 1) Specify the experiment folder (where all data from single
% experiment is saved) and trial folder (specific folder where trial to be
% analyzed is saved). If these are the same, just set trial_folder =
% exp_folder. 

% Path to data and ROIs
exp_folder = fullfile(getDataFold,'240312','GluSnFR StimMini','Dish 3');
trial_folder = exp_folder; 
% 2) specify file name of your recording
rec_name = 'GluSnFR3(6).tif'; % name of recording file, if left empty, grabs first file in trial_folder

% 3) Specify ROI set zip file (output of saving ROIs in ImageJ)
roiset_name = '031224_Dish3_RoiSet_GluSnFR(4)';

% 4) Analysis script settings
save_mini_output = 1; % Set to 1 to save mini output to spreadsheets and .mat file
plot_img = 1; % Set to 1 to plot mean F image with  ROIs first, 0 to skip
save_figs = 1; % Set to 1 to save images generated by this script, 0 to skip
mot_correct = 0; % motion correction - SLOW, usually not necessary

% 5) Specify your sampling rate and frames at which stimuli were applied.
% If no stimuli were applied, leave stim_times, stim_wind, and baseline_wind blank
% Experiment/imaging settings
sampling_rate = 25; % Hz
stim_times = 2:2:28;
stim_wind = 0.3; % sec to analyze after each stim (also gets blanked in detectMinis)
baseline_wind = 0.1; % sec for baseline window 
units = 'sec'; % 'sec' or 'frames'
exp_settings = ExperimentSettings(stim_times,stim_wind,baseline_wind,units,sampling_rate); 
%% Use plotTrials to plot diff image, calculate and plot ROI fluorescent 
% traces, and save for reloading 

ps = plotTrialSettings; 
ps.show_diff_image = [1,2,4]; % 1 - baseline, 2 - peak, 3 - diff (peak - baseline), 4 - mean diff (for multiple stimuli)
ps.filt_width = 0; 
ps.funcs = {'mean','baseline','deltaF_F0'};
ps.roi_func_mode =  'separate';
ps.save_processed_data = 1;
ps.load_processed_data = 1; % To rerun analysis on raw image, set this to 0
                            % otherwise plotTrial will load your previous
                            % processed data (e.g. mean F traces in in your ROIs)
ps.save_fig = 2; % 2 to save figures, 0 to just plot
ps.plot_func = 'deltaF_F0';
ps.roiset_filedir = exp_folder;
ps.roi_func_fig_size = [47 26];
ps.offset_factor = 0.5 ; 
ps.show_roi_labels = 1; 
ps.x_lim = [-0.5 27.5]; % t = 0 is set to first stimulus time
ps.motion_correct = mot_correct;
trial_data = plotTrial(fullfile(exp_folder,rec_name),exp_settings,roiset_name,...
                        [],ps);
%% Run mini detection
% 6) Description of settings are below. Most can be left to defaults, main
% settings you may want to adjust are threshold, snr_thresh, nframes_back,
% nframes_forward, min_mini_width, deconv_tau (all described below)
% for visualization and saving, set the plot_filt_output_roi_index and
% plot_figs variables
% Mini detector settings
preset_name = '';
if isempty(preset_name)
    % Set parameters manually
    settings = struct();
    % Peak detection
    settings.threshold = 3; % threshold for peak detection on filtered trace. 
                            % Defined as multiple above noise level (std of
                            % baseline fluctations)
    settings.snr_thresh = 5; % throw out minis with 
                             % mini SNR (peak/std(baseline)) less than this number 
                             % (based on raw F trace). Set to 0 to skip this. 
    settings.nframes_back = round(0.2*sampling_rate); % number of frames before each mini peak to extract
    settings.nframes_forward = round(0.4*sampling_rate); % number of frames after each mini peak to extract
    settings.mini_width_range = [0.04 0.3]; % sec - minimum peak width, 
                                                % using findpeaks.m definition of width (default 'halfprom')
    settings.min_peak_distance = 2/sampling_rate; % sec - min distance between mini peaks to allow (default 0.05 sec)
    settings.max_mini_amp = 0; % deltaF/F - max amplitude to exclude massive unknown events
    settings.mini_peak_prominence = 5; % optional criteria, peak prominence, set to 0 to turn off
    % Filtering
    settings.deconv = 0; % set to 1 to use deconvolution, may need to adjust threshold if turned off
    settings.apply_filter = 0;
    settings.filt_type = 'butter'; % filter type, 'gauss' for gaussian or 'butter' for butterworth
    settings.refilter_deconv = 0; % 1 to refilter deconvolved trace (usually doesn't have much effect, can skip)
    settings.smooth_filt_width = 0; % width of median smoothing filter, takes 
                                    % moving median of this number of frames,
                                    % usually not needed, especially if using
                                    % lower sampling rate, b/c it can cause
                                    % smooth out peaks too much
    settings.fc = [0.01]; % Hz - highpass filter cutoff frequences, gets rid 
                         % of baseline fluctuations
    settings.filt_order = 1; 
    settings.deconv_tau = 100e-3; % ms decay time constant for deconvolution. 
                                  % Uses single exponential decay with this
                                  % time constant to enhance SNR of events with
                                  % similar shape, time constant should match
                                  % decay time constant of minis in your
                                  % recordings, which can be measured after
                                  % detection below
    % Clean up
    settings.stim_frames = exp_settings.stim_vals; % ignore if no stim
    settings.blank_around_stim = [exp_settings.baseline_wind,exp_settings.stim_wind]; % ignore if no stim
    % settings.find_pk_frame = round(0.12*sampling_rate);% look 120 ms around peak from filtered F in raw F to get actual peak time                              
    settings.find_pk_frame = 0; 
    settings.num_frames_skip_start = 1; % frames to remove from start due to filtering artifacts
    settings.num_frames_skip_end = 1; % frames to remove from end due to filtering artifacts
    settings.use_asls_baseline = 1;  % 1  to use asymmetric least squares baseline removal
                                     % 0 uses simple average of nframes_back
                                     % frames before each peak, may be less
                                     % robust for minis immediately after other
                                     % minis
    settings.asls_smoothness = 5; % smoothness param for asymmetric least squares (see asLS_baseline.m for description)
    settings.asls_asym = 0.1; % asymmetry parameter for asymmetric least squares
    settings.est_rise_time_frames = 1; % take baseline this many frames before peak (typical rise time of GluSnFR3 signal)
    % plotting and file saving
    settings.plot_filt_output_roi_index = 32; % plot example of filtering in this roi
    settings.plot_figs = 1; % 1 to plot mini detection figures, 0 to skip
    settings.save_figs = save_figs; % 1 to save figures, 0 to skip
    settings.save_figs_dir = fullfile(trial_data.recording.filedir,'mini_analysis'); % save figures to this directory (saves to current directory if empty)
    settings.trial_name = trial_data.recording.img_name; % for file saving
    settings.print_level = 1; 
else
    settings = detectMinisPresets(preset_name,exp_settings.sampling_rate);
end
% Run 
mini_output = detectMinis(trial_data.func_output.mean,exp_settings.sampling_rate,settings); 
% Output mini data to .mat file and spreadsheet
if save_mini_output    
    saveMiniOutput(mini_output,trial_data.recording,trial_data.rois,exp_settings);
end
%% Plot traces in all with minis overlaid
% set offset factor for traces automatically, but if this doesn't work, may
%  need to set manually
offset_factor = 100; 
% offset_factor = max(max(func_output.mean,[],1)-mean(func_output.mean,1))*1.1; 
fig = figure('Units','inches','Position',[0.4479    1.3021   19.0625    8.9583]); 
ax = gca;
plotROIfunc(trial_data.func_output,'mean',exp_settings.stim_vals,...
            [],'ax',ax,...
            'show_legend',0,'rois',trial_data.rois,'offset_factor',offset_factor,...
            'sbar_len',offset_factor/2,'title_on',0);
offset = linspace(trial_data.rois.num_rois*offset_factor,...
                                    0,trial_data.rois.num_rois);
cols = lines(trial_data.rois.num_rois);
for i = 1:trial_data.rois.num_rois
    Fi = trial_data.func_output.mean(:,i);
    non_nan_frames = find(~isnan(Fi));
    Fi = Fi - Fi(non_nan_frames(1),:) + offset(i); % start all traces at 0 for plot    
    if ~isempty(mini_output.mini_frames{i})
%         mini_heightsi = max(mini_output.mini_F_traces_roi{i},[],1)' - mean(mini_output.mini_F_traces_roi{i}(1:settings.nframes_back,1))';
        
        plot(mini_output.mini_frames{i},Fi(mini_output.mini_frames{i}),'o','MarkerEdgeColor',cols(i,:),...
                'MarkerFaceColor','k','MarkerSize',6);
    end
end
if save_figs
    printFig(fig,fullfile(trial_data.recording.filedir,'mini_analysis'),...
            [trial_data.recording.img_name,'_meanF_with_minis'])
end